### ISSUE TITLE
org/parboiled/errors/ParserRuntimeException

### ISSUE THREAD

**Issue by jhawkinsatgood** [Abnaxos/pegdown-doclet#26]
Hi,
I'm completely new to javadocs and am trying to use the pegdown-doclet plugin. When I run javadocs like:
JAVA_HOME=`/usr/libexec/java_home` /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin/javadoc -d javadoc/
  -sourcepath ~/path/to/my/src/
  -doclet ch.raffael.doclets.pegdown.PegdownDoclet
  -docletpath /path/to/download/and/then/pegdown-doclet-master/target/classes/ 
  com.fully.qualified.name.of.my.package

I get the following error:
java.lang.NoClassDefFoundError: org/parboiled/errors/ParserRuntimeException
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
    at java.lang.Class.getMethod0(Class.java:2813)
    at java.lang.Class.getMethod(Class.java:1663)
    at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:257)
    at com.sun.tools.javadoc.DocletInvoker.optionLength(DocletInvoker.java:184)
    at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:347)
    at com.sun.tools.javadoc.Start.begin(Start.java:167)
    at com.sun.tools.javadoc.Main.execute(Main.java:59)
    at com.sun.tools.javadoc.Main.main(Main.java:49)
Caused by: java.lang.ClassNotFoundException: org.parboiled.errors.ParserRuntimeException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 10 more
javadoc: error - fatal error
1 error

I am running on Mac OSX and built the plugin by running mvn install. My maven version is:
JAVA_HOME=`/usr/libexec/java_home` mvn -version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 13:51:28+0000)
Maven home: /opt/local/share/java/maven3
Java version: 1.7.0_60, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.3", arch: "x86_64", family: "mac"

Sorry, I'm probably missing something basic.

Thanks in advance, Jim

**Comment by gherson** [comment]
Couldn't shake that NoClassDefFoundError from IntelliJ's Generate Javadoc tool until, under its "Other command line arguments", I concatenated all the filespecs of the needed jars:
-doclet ch.raffael.doclets.pegdown.PegdownDoclet -docletpath C:/Users/me/Practice/lib/pegdown-doclet-1.2.1.jar;C:/Users/me/Practice/lib/parboiled-core-1.1.5.jar;C:/Users/me/Practice/lib/parboiled-java-1.1.5.jar;C:/Users/me/Practice/lib/pegdown-1.4.1.jar;C:/Users/me/Practice/lib/asm-4.1.jar;C:/Users/me/Practice/lib/asm-analysis-4.1.jar;C:/Users/me/Practice/lib/asm-tree-4.1.jar;C:/Users/me/Practice/lib/asm-util-4.1.jar;C:/Users/me/Practice/lib/guava-18.0.jar;C:/Users/me/Practice/lib/plantuml-8031.jar;C:/Users/me/Practice/lib/tools.jar
fyi.
(On Unix, swap the semis for colons)
