### ISSUE TITLE
Assertion failed at PsiParameterListImpl.getParameterIndex at PegdownDocumentationProvider.generateDoc

### ISSUE THREAD

**Issue by HaasJona** [Abnaxos/pegdown-doclet#52]
```
Assertion failed
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:156)
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:165)
    at com.intellij.psi.impl.source.PsiParameterListImpl.getParameterIndex(PsiParameterListImpl.java:50)
    at com.intellij.psi.util.PsiFormatUtil.getExternalName(PsiFormatUtil.java:446)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.getExternalName(BaseExternalAnnotationsManager.java:80)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.doCollect(BaseExternalAnnotationsManager.java:208)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.collectExternalAnnotations(BaseExternalAnnotationsManager.java:146)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.findExternalAnnotations(BaseExternalAnnotationsManager.java:123)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateAnnotations(JavaDocInfoGenerator.java:918)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateMethodParameterJavaDoc(JavaDocInfoGenerator.java:1058)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfoCore(JavaDocInfoGenerator.java:396)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfo(JavaDocInfoGenerator.java:437)
    at com.intellij.lang.java.JavaDocumentationProvider.generateExternalJavadoc(JavaDocumentationProvider.java:554)
    at com.intellij.lang.java.JavaDocumentationProvider.generateDoc(JavaDocumentationProvider.java:542)
    at ch.raffael.doclets.pegdown.integrations.idea.PegdownDocumentationProvider.generateDoc(PegdownDocumentationProvider.java:135)
    at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$9$1.run(CtrlMouseHandler.java:666)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler$9.run(CtrlMouseHandler.java:661)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:389)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

running IntelliJ Idea 2016.1 RC1

**Comment by HaasJona** [comment]
Also happening in latest Idea 2016.1
```
Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:156)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:165)
	at com.intellij.psi.impl.source.PsiParameterListImpl.getParameterIndex(PsiParameterListImpl.java:50)
	at com.intellij.psi.util.PsiFormatUtil.getExternalName(PsiFormatUtil.java:446)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.getExternalName(BaseExternalAnnotationsManager.java:80)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.doCollect(BaseExternalAnnotationsManager.java:208)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.collectExternalAnnotations(BaseExternalAnnotationsManager.java:146)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.findExternalAnnotations(BaseExternalAnnotationsManager.java:123)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateAnnotations(JavaDocInfoGenerator.java:918)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateMethodParameterJavaDoc(JavaDocInfoGenerator.java:1058)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfoCore(JavaDocInfoGenerator.java:396)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfo(JavaDocInfoGenerator.java:437)
	at com.intellij.lang.java.JavaDocumentationProvider.generateExternalJavadoc(JavaDocumentationProvider.java:554)
	at com.intellij.lang.java.JavaDocumentationProvider.generateDoc(JavaDocumentationProvider.java:542)
	at ch.raffael.doclets.pegdown.integrations.idea.PegdownDocumentationProvider.generateDoc(PegdownDocumentationProvider.java:135)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$9$1.run(CtrlMouseHandler.java:666)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$9.run(CtrlMouseHandler.java:661)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Abnaxos** [comment]
To reproduce: Ctrl-Q on a parameter.

**Comment by slovdahl** [comment]
Would you mind publishing a new version of the plugin with this bug fix included?

**Comment by Abnaxos** [comment]
Sorry, completely forgot releasing it. Done now.
