### ISSUE TITLE
Error: "Illegal group reference"

### ISSUE THREAD

**Issue by greenlaw110** [Abnaxos/pegdown-doclet#70]
I am building my [project](https://github.com/actframework/actframework) and encountered the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9:javadoc (gen-javadoc) on project act: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - Picked up JAVA_TOOL_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
[ERROR] javadoc: error - In doclet class ch.raffael.doclets.pegdown.PegdownDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
[ERROR] java.lang.IllegalArgumentException: Illegal group reference
[ERROR] at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
[ERROR] at ch.raffael.doclets.pegdown.Tags.insertInlineTags(Tags.java:134)
[ERROR] at ch.raffael.doclets.pegdown.Options.toHtml(Options.java:482)
[ERROR] at ch.raffael.doclets.pegdown.PegdownDoclet.defaultProcess(PegdownDoclet.java:358)
[ERROR] at ch.raffael.doclets.pegdown.PegdownDoclet.processMember(PegdownDoclet.java:319)
[ERROR] at ch.raffael.doclets.pegdown.PegdownDoclet.processClass(PegdownDoclet.java:304)
[ERROR] at ch.raffael.doclets.pegdown.PegdownDoclet.process(PegdownDoclet.java:221)
[ERROR] at ch.raffael.doclets.pegdown.PegdownDoclet.start(PegdownDoclet.java:136)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
[ERROR] at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:219)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:205)
[ERROR] at com.sun.tools.javadoc.Main.execute(Main.java:64)
[ERROR] at com.sun.tools.javadoc.Main.main(Main.java:54)
```

Any idea?

**Comment by greenlaw110** [comment]
never mind, it is triggered by javadoc of one of my java source code. I've smashed it although I don't know which part exactly caused the trouble.

**Comment by greenlaw110** [comment]
Two years later I've got the same issue and happened to read my own issue report. Just to document what happened this time for future reference:

The issue is caused by using `{@link $...}` in the javadoc. Where `$` is a class name. Somehow Markdown doclet is not able to handle that pattern.

Here is how to debug this kind of error:

1. run `mvn javadoc:javadoc` to generate required javadoc scripts in `target/site/apidoc` dir. You will get error, but that's okay

2. Create whatever class with a main method, looks like:

```java
public class DebugJavaDoc {
    public static void main(String[] args) {
        String[] sa = {"@options", "@packages"};
        com.sun.tools.javadoc.Main.execute(sa);
    }
}
```

3. set the working directory in IDEA:
![image](https://user-images.githubusercontent.com/216930/30245135-bbcc896a-9613-11e7-9574-83644456e690.png)

4. Set breakpoint in the error place and debug the class.
